blank_issues_enabled: true
contact_links:
  - name: Aggarly Organization Discussions
    url: https://github.com/orgs/Aggarly-ORG/discussions
    about: Ask architectural questions and discuss ideas with the team.
