package com.luna.aggarly.aiagent.engine.enums;

public enum IntentCategory {
    PROPERTY_SEARCH,
    PROPERTY_QUESTION,
    PROPERTY_COMPARISON,
    BOOKING_ACTION,
    AVAILABILITY_QUESTION,
    REVIEW_REQUEST,
    HOST_MANAGEMENT,
    ADMIN_MANAGEMENT,
    IMAGE_ANALYSIS,
    DOCUMENT_ANALYSIS,
    MESSAGING_ASSIST,
    NOTIFICATION_REQUEST,
    SUPPORT_QUESTION,
    TRAVEL_PLANNING,
    PLATFORM_NAVIGATION,
    EXPLAIN_DECISION,
    MEMORY_MANAGEMENT,
    MULTI_STEP_COMPLEX,
    SCHEDULE_AUTOMATION,
    SMALL_TALK
}
